# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "819a4f61c71a7a21adf004cda3437867"
name = "Incode Track"
application_url = "https://example.com"
embedded = true

[sidekick]
extensions_summary = "Inspect delivery coverage, ETA settings, fulfillment locations, shipping methods, and delivery lookup performance"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
  uri = "/webhooks/privacy"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,read_locations,read_orders,read_products,read_shipping,write_app_proxy,write_orders"

[auth]
redirect_urls = [ "https://example.com/auth/callback" ]

[app_proxy]
url = "/apps/delivery-checker"
subpath = "delivery-checker"
prefix = "apps"
