# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "819a4f61c71a7a21adf004cda3437867"
name = "ETADeliverPickup"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  uri = "/webhooks/privacy"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,read_locations,read_orders,read_products,read_themes,write_app_proxy"

[auth]
redirect_urls = [ "https://example.com/auth/callback" ]

[app_proxy]
url = "https://example.com/apps/delivery-checker"
subpath = "delivery-checker"
prefix = "apps"

[sidekick]
extensions_summary = "Inspect delivery coverage, ETA settings, fulfillment locations, shipping methods, and delivery lookup performance"
